Controllers/DepartmentController.cs
using ems.Data;
using ems.Models;
using System.Threading.Tasks;
using ems.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using ems.Helpers.Alert;
using Microsoft.AspNetCore.Authorization;
using ems.Helpers.Permissions;

namespace ems.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly ApplicationContext _context;

        public DepartmentController(ApplicationContext context)
        {
            _context = context;
        }

        [Authorize(Permissions.Department.Create)]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Permissions.Department.List)]
        public async Task<IActionResult> IndexAsync()
        {
            var departments = await _context.Departments.Select(d => new DepartmentViewModel
            {
                Name = d.Name,
                Description = d.Description,
                Id = d.Id

            }).ToListAsync();
            return View(departments);
        }

        [HttpGet]
        [Authorize(Permissions.Department.Edit)]
        public async Task<IActionResult> EditAsync(int id)
        {
            var departmentVm = (await _context.Departments
                .FirstOrDefaultAsync(d => d.Id == id))
                .ToViewModel();

            if (departmentVm == null)
            {
                return NotFound();
            }
            return View(departmentVm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Permissions.Department.Delete)]

        public async Task<IActionResult> DeleteAsync(int id)
        {
            var department = await _context.Departments.FirstOrDefaultAsync(d => d.Id == id);
            if (department == null)
            {
                return BadRequest();
            }
            _context.Entry(department).State = EntityState.Deleted;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index")
            .WithSuccess("congrats", "the department was deleted successfully");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Permissions.Department.Edit)]

        public async Task<IActionResult> Edit(int id, DepartmentViewModel departmentVm)
        {
            if (!ModelState.IsValid)
            {
                return View(departmentVm);
            }

            var department = await _context.Departments.AsNoTracking().FirstOrDefaultAsync(d => d.Id == id);
            if (department == null)
            {
                return BadRequest();
            }
            department = departmentVm.ToModel();
            _context.Entry(department).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Permissions.Department.Create)]

        public async Task<IActionResult> CreateAsync(DepartmentViewModel departmentVm)
        {
            if (!ModelState.IsValid)
            {
                return View(departmentVm);
            }
            var department = departmentVm.ToModel();
            _context.Departments.Add(department);
            await _context.SaveChangesAsync();
            return LocalRedirect("~/").WithSuccess("hurray", $"new Department {department.Name} created");
            // return AlertExtensions.WithSuccess(LocalRedirect("~/"), "hurray", "$new Department {department.Name} created");
        }
    }
}

Controllers/LeaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ems.Data;
using ems.Handlers;
using ems.Helpers;
using static ems.Helpers.LeaveRequirement.LeaveRequirementHelpers;
using ems.Helpers.Alert;
using ems.Helpers.Permissions;
using ems.Models;
using ems.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using static ems.Models.Leave;

namespace ems.Controllers
{
    public class LeaveController : Controller
    {
        private ApplicationContext _context;
        private readonly ILogger<LeaveController> _logger;
        private readonly IAuthorizationService _authorizationService;

        public LeaveController(ApplicationContext context, ILogger<LeaveController> logger, IAuthorizationService authorizationService)
        {
            _context = context;
            _logger = logger;
            _authorizationService = authorizationService;
        }

        [HttpGet]
        public async Task<IActionResult> CreateAsync()
        {
            LeaveCreateIndexViewModel vm = new LeaveCreateIndexViewModel();
            vm.MyLeaves = await GetMyLeaves();
            return View(vm);
        }


        private async Task<List<LeaveViewModel>> GetMyLeaves()
        {
            var ownerId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var allLeaves = await _context.Leaves
                .Include(l => l.Reply)
                .Include(l => l.Owner)
                .Where(l => l.OwnerId == ownerId)
                .Select(l => l.ToViewModel())
                .ToListAsync();
            return allLeaves;

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync([Bind(Prefix = "LeaveViewModel")] LeaveViewModel leaveVm)
        {
            LeaveCreateIndexViewModel vm = new LeaveCreateIndexViewModel();
            vm.LeaveViewModel = leaveVm;

            if (!ModelState.IsValid)
            {
                vm.MyLeaves = await GetMyLeaves();
                return View(vm);

            }
            var leave = leaveVm.ToModel();
            leave.OwnerId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _context.Leaves.Add(leave);
            await _context.SaveChangesAsync();
            return LocalRedirect("~/")
                .WithSuccess("hurray", $"new {EnumHelper<LeaveType>.GetDisplayValue(leave.Type)} created");
        }

        [HttpGet]
        [Authorize(Permissions.Leave.List)]
        public async Task<IActionResult> IndexAsync()
        {
            var leaves = await _context.Leaves
                .Include(l => l.Owner)
                .Include(l => l.Reply)
                .Select(leave => leave.ToViewModel())
                .AsNoTracking()
                .ToListAsync();
            return View(leaves);
        }

        [HttpGet]
        public async Task<IActionResult> EditAsync(int id)
        {
            var leave = await _context.Leaves
                .Include(l => l.Reply)
                .FirstOrDefaultAsync(l => l.Id == id);
            if (leave == null)
                return NotFound();

            var authorizationResult = await _authorizationService.AuthorizeAsync(User, leave, GetRequirementForLeave(leave));
            if (authorizationResult.Succeeded)
            {
                var leaveVm = leave.ToViewModel();
                return View(leaveVm);
            }
            else if (User.Identity.IsAuthenticated)
            {
                return new ForbidResult();
            }
            else
            {
                return new ChallengeResult();
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAsync(int id, LeaveViewModel leaveVm)
        {
            if (!ModelState.IsValid)
            {
                return View(leaveVm);
            }
            var leave = await _context.Leaves
                .Include(l => l.Owner)
                .Include(l => l.Reply)
                .AsNoTracking()
                .FirstOrDefaultAsync(l => l.Id == id);

            if (leave == null)
            {
                return BadRequest();
            }
            var authorizationResult = await _authorizationService.AuthorizeAsync(User, leave, GetRequirementForLeave(leave));
            if (authorizationResult.Succeeded)
            {

                leave = leaveVm.ToModel();
                leave.OwnerId  =User.FindFirstValue(ClaimTypes.NameIdentifier);
                _context.Entry(leave).State = EntityState.Modified;

                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home").WithSuccess("hurray", $"leave with id {leave.Id} was updated");
            }
            else if (User.Identity.IsAuthenticated)
            {
                return new ForbidResult();
            }
            else
            {
                return new ChallengeResult();
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var leave = await _context.Leaves
                .Include(l => l.Owner)
                .Include(l => l.Reply)
                .FirstOrDefaultAsync(l => l.Id == id);
            if (leave == null)
                return BadRequest();

            var authorizationResult = await _authorizationService.AuthorizeAsync(User, leave, GetRequirementForLeave(leave));
            if (authorizationResult.Succeeded)
            {
                _context.Entry(leave).State = EntityState.Deleted;
                await _context.SaveChangesAsync();
                return RedirectToAction("Create").WithSuccess("", $"leave with id {id} deleted successfully");

            }
            else if (User.Identity.IsAuthenticated)
            {
                return new ForbidResult();
            }
            else
            {
                return new ChallengeResult();
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DecisionAsync(int id, string description, Models.Reply.ReplyStatus status)
        {
            var leave = await _context.Leaves.Include(l => l.Reply).FirstOrDefaultAsync(l => l.Id == id);
            if (leave == null)
            {
                return BadRequest();
            }
            var reply = leave.Reply;
            if (reply == null)
            {
                reply = new Reply();
                reply.LeaveId = leave.Id;
                reply.Status = status;
                reply.Description = description;
                _context.Entry(reply).State = EntityState.Added;
            }
            else
            {
                reply.Status = status;
                reply.Description = description;
                _context.Entry(reply).State = EntityState.Modified;

            }

            _logger.LogInformation(_context.Entry(reply).State.ToString());
            await _context.SaveChangesAsync();
            return RedirectToAction("Index").WithSuccess("", $"leave with id {id} {status.ToString()}");
        }
    }
}

Controllers/MailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ems.Data;
using ems.Helpers.Alert;
using ems.Helpers.Permissions;
using ems.Models;
using ems.Services;
using ems.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using static ems.ViewModels.MailViewModel;

namespace ems.Controllers
{
    [Route("[controller]")]
    [Authorize(Permissions.Mail)]
    public class MailController : Controller
    {
        private readonly ILogger<MailController> _logger;
        private readonly IMailService _mailService;
        private readonly ApplicationContext _context;

        public MailController(
            ILogger<MailController> logger,
            IMailService mailService,
            ApplicationContext context)
        {
            _logger = logger;
            _mailService = mailService;
            _context = context;
        }

        public async Task<IActionResult> CreateAsync()
        {
            var departments = await _context.Departments.Select(d => new SelectListItem
            {
                Text = d.Name,
                Value = d.Id.ToString()
            }).ToListAsync();

            var users = new List<SelectListItem>()
            {
              new  SelectListItem{Text="User1", Value="randomGuid1"},
              new  SelectListItem{Text="User2", Value="randomGuid2"},
              new  SelectListItem{Text="User3", Value="randomGuid3"},
              new  SelectListItem{Text="User3", Value="randomGuid4"},
            };

            var mailViewModel = new MailViewModel();
            mailViewModel.Departments = departments;
            mailViewModel.Users = users;
            return View(mailViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync(MailViewModel Vm)
        {
            if (!ModelState.IsValid)
            {
                return View(Vm);
            }
            List<string> toEmails = new List<string>();
            switch (Vm.Receiver)
            {
                case ReceiverType.All:
                    toEmails = new List<string>() { "fetch_first_user", "fetch_second_user", "fetch_third_user", "fetch_all" };
                    break;
                case ReceiverType.Department:
                    var departmentId = Vm.ResourceId;
                    toEmails = new List<string>() { "dept_user1", "dept_user2", "dept_user3" };
                    break;
                case ReceiverType.Staff:
                    var staffId = Vm.ResourceId;
                    toEmails = new List<string>() { "teststaff@test.com" };
                    break;

            }
            try
            {
                var mailRequest = new MailRequest
                {
                    Body = Vm.Body,
                    Subject = Vm.Subject,
                    ToEmails = toEmails.ToArray(),
                    Attachments = Vm.Files

                };
                await _mailService.SendMailAsync(mailRequest);
            }
            catch (Exception ex)
            {
                throw;
            }
            _logger.LogInformation("sending mail");
            return LocalRedirect("~/").WithSuccess(string.Empty, $"mail send successfully");
        }

    }
}

Controllers/NoticeController.cs
using ems.Data;
using ems.Helpers.Alert;
using ems.Helpers.Permissions;
using ems.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ems.Controllers
{
    public class NoticeController : Controller
    {
        private readonly ApplicationContext _context;

        public NoticeController(ApplicationContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> IndexAsync()
        {
            var notices = await _context.Notices
                .Include(n => n.Owner)
                .Select(n => n.ToViewModel())
                .AsNoTracking()
                .ToListAsync();
            return View(notices);
        }

        [HttpGet]
        [Authorize(Permissions.Notice.Create)]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> EditAsync(int id)
        {
            var notice = (await _context.Notices.FirstOrDefaultAsync(n => n.Id == id)).ToViewModel();
            return View(notice);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAsync(int id, NoticeViewModel noticeVm)
        {
            if (!ModelState.IsValid)
            {
                return View(noticeVm);
            }
            var notice = await _context.Notices.AsNoTracking().FirstOrDefaultAsync(n => n.Id == id);
            if (notice == null)
            {
                return BadRequest();
            }
            notice = noticeVm.ToModel();
            _context.Entry(notice).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index").WithSuccess(string.Empty, $"notice with id {id} edited");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var notice = await _context.Notices.FirstOrDefaultAsync(n => n.Id == id);
            if (notice == null)
                return BadRequest();
            _context.Entry(notice).State = EntityState.Deleted;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index").WithSuccess(string.Empty, $"notice with id {id} deleted");

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Permissions.Notice.Create)]

        public async Task<IActionResult> CreateAsync(NoticeViewModel noticeVm)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!ModelState.IsValid)
            {
                return View(noticeVm);
            }
            var notice = noticeVm.ToModel();
            notice.OwnerId = userId;
            _context.Notices.Add(notice);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home").WithSuccess("", "new notice created");

        }

    }
}

Views/Shared/_AlertPartial.cshtml
@{
    var type = TempData["alert-type"];
    var body = TempData["alert-body"];
    var title = TempData["alert-title"];
}
@if(type !=null)
{
    <div class="alert alert-@type show">
        <strong> @title  </strong> @body
        <a data-dismiss="alert" class="close">&times;</a>
    </div>
}

Views/Shared/_DeleteConfirmationModal.cshtml
<div class="modal hide fade" id="delete-modal" role="dialog">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Modal header</h3>
    </div>
    <div class="modal-body">
        <p>Are you sure you want to delete this <span id="resource-name"></span>?</p>
    </div>
    <div class="modal-footer">
        <button  class="btn btn-outline-primary" data-dismiss="modal">Close</button>
        <form id="delete-form" method="POST" style="display: inline-block;">
            <button type="submit" class="btn btn-outline-danger">Delete</button>
        </form>
    </div>
</div>

@using (Html.BeginScripts())
{
    <script>
        Object.values(document.querySelectorAll('a[href="#delete-modal"]')).forEach(function (toggler) {
        toggler.addEventListener("click", function (event) {
            @* event.stopPropagation(); *@
            var deleteModal = document.querySelector(event.target.getAttribute("href"));
            deleteModal.dataset.action = toggler.dataset.action;
            deleteModal.dataset.resourceId = toggler.dataset.resourceId
            deleteModal.dataset.resourceName = toggler.dataset.resourceName
    })
    });
    $('#delete-modal').on('show', function (event) {
        console.log("modal show method called");
        var form = document.getElementById("delete-form");
        var action =  this.dataset.action; 
        document.getElementById("resource-name").innerHTML = this.dataset.resourceName;
        form.setAttribute("action", action);
    })
</script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title-ems</title>
    <link type="text/css" href="~/lib/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link type="text/css" href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link type="text/css" href="~/css/theme.css" rel="stylesheet">
    <link type="text/css" href="~/images/icons/css/font-awesome.css" rel="stylesheet">
    <link type="text/css" href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
        rel='stylesheet'>
    <link rel="stylesheet" href="~/css/site.css">
    @RenderSection("Stylesheets", false)
</head>
<nav class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a asp-action="Home" asp-controller="Home" asp-area="" class="brand" style="text-transform: uppercase;">Ems
            </a>
            <a href="never-get-here.html" class="sidebar-toggler" id="sidebar-toggler"
                style="font-size: 1.4rem; display:inline-block; padding:20px; margin-left:9rem;"> &#x2630; </a>
            <partial name="_SignedInPartial"></partial>
            <form class="navbar-search pull-right input-append" action="#">
                <input type="text" class="span3" placeholder="Search for....">
                <button class="btn btn-primary" type="button">
                    <i class="icon-search"></i>
                </button>
            </form>
        </div>
    </div>
    </div>
</nav>

<body>
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="span3">
                    <div class="sidebar anim-sidebar" id="sidebar">
                        <div class="widget-container">
                            <p class="widget-header">Core</p>
                            <ul class="widget widget-menu unstyled">
                                <li class="active">
                                    <a asp-action="Index" asp-controller="Home" asp-area=""><i
                                            class="menu-icon icon-dashboard"></i>Dashboard</a>
                                </li>
                            </ul>
                        </div>
                        <div class="widget-container">
                            <p class="widget-header">Interface</p>
                            <ul class="widget widget-menu unstyled">
                                <li>
                                    <a class="collapsed" data-toggle="collapse" href="#toggleDepartmentLinks">
                                        <i class="menu-icon icon-building"></i>
                                        <i class="icon-chevron-down pull-right"></i>
                                        <i class="icon-chevron-up pull-right"></i>
                                        Departments </a>
                                    <ul id="toggleDepartmentLinks" class="collapse unstyled">
                                        <li>
                                            <a asp-action="Create" asp-controller="Department" asp-area="">Create </a>
                                        </li>
                                        <li>
                                            <a asp-action="Index" asp-controller="Department" asp-area="">View</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a class="collapsed" data-toggle="collapse" href="#toggle-users-section">
                                        <i class="menu-icon icon-user"></i>
                                        <i class="icon-chevron-down pull-right"></i>
                                        <i class="icon-chevron-up pull-right"></i>
                                        User </a>
                                    <div id="toggle-users-section" class="collapse unstyled">
                                        <a class="collapsed" data-toggle="collapse" href="#toggleRoles">
                                            <i class="icon-chevron-down pull-right"></i>
                                            Role </a>
                                        <ul id="toggleRoles" class="collapse unstyled">
                                            <li><a asp-action="Create" asp-controller="Role" asp-area="Identity">Create
                                                </a></li>
                                            <li><a asp-action="Index" asp-controller="Role" asp-area="Identity">View
                                                </a></li>
                                        </ul>
                                        <a class="collapsed" data-toggle="collapse" href="#toggleUsers">
                                            <i class="icon-chevron-down pull-right"></i>
                                            Users </a>
                                        <ul id="toggleUsers" class="collapse unstyled">
                                            <li><a asp-action="Create" asp-controller="Account"
                                                    asp-area="Identity">Create </a></li>
                                            <li><a asp-action="Index" asp-controller="Account" asp-area="Identity">View
                                                </a>
                                            </li>
                                        </ul>
                                        <a class="collapsed" data-toggle="collapse" href="#togglePermissions">
                                            <i class="icon-chevron-down pull-right"></i>
                                            Persmission </a>
                                        <ul id="togglePermissions" class="collapse unstyled">
                                            <li><a asp-action="Index" asp-controller="Permission"
                                                    asp-area="Identity">View </a>
                                            </li>
                                        </ul>
                                    </div>
                                </li>
                                <li>
                                    <a class="collapsed" data-toggle="collapse" href="#toggleLeaves">
                                        <i class="menu-icon icon-lock"></i>
                                        <i class="icon-chevron-down pull-right"></i>
                                        <i class="icon-chevron-up pull-right"></i>
                                        Staff Leave </a>
                                    <ul id="toggleLeaves" class="collapse unstyled">
                                        <li><a asp-action="Index" asp-controller="Leave" asp-area="">Approve Leave </a></li>
                                        <li><a asp-action="Create" asp-controller="Leave" asp-area="">Create Leave</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a class="collapsed" data-toggle="collapse" href="#toggleNotices">
                                        <i class="menu-icon icon-pencil"></i>
                                        <i class="icon-chevron-down pull-right"></i>
                                        <i class="icon-chevron-up pull-right"></i>
                                        Staff Notices</a>
                                    <ul id="toggleNotices" class="collapse unstyled">
                                        <li><a asp-action="Index" asp-controller="Notice" asp-area="">View Notice </a>
                                        </li>
                                        <li><a asp-action="Create" asp-controller="Notice" asp-area="">Create Notice
                                            </a></li>
                                    </ul>
                                </li>
                                <li><a asp-controller="Mail" asp-action="Create"><i
                                            class="menu-icon icon-envelope"></i>Mail </a></li>
                            </ul>
                        </div>
                    </div>
                    <!--/.sidebar-->
                </div>
                <!--/.span3-->
                <div class="span9">
                    <partial name="_AlertPartial"></partial>
                    @RenderBody()
                </div>
                <!--/.span9-->
            </div>
        </div>
        <!--/.container-->
    </div>
    <!--/.wrapper-->

    <script src="~/js/scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/js/toggle-sidenav.js"></script>
    @RenderSection("Scripts", false)
    @Html.PageScripts()

</body>
<footer class="footer">
    <div class="container">
        <b class="copyright">&copy; 2020 Ems </b>All rights reserved.
    </div>
</footer>

</html>

Views/Shared/_PagingJavascriptImports.cshtml
<script src="~/js/scripts/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
<script src="~/js/scripts/flot/jquery.flot.js" type="text/javascript"></script>
<script src="~/js/scripts/flot/jquery.flot.resize.js" type="text/javascript"></script>
<script src="~/js/scripts/datatables/jquery.dataTables.js" type="text/javascript"></script>
<script src="~/js/scripts/common.js" type="text/javascript"></script>

Views/Shared/_SignedInPartial.cshtml
@inject SignInManager<ApplicationUser> _signInManager
@inject UserManager<ApplicationUser> _userManager
<ul class="nav pull-right m-3">
    @if(_signInManager.IsSignedIn(User)){
        <li class="nav-user dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span style="vertical-align:top;">@(_userManager.GetUserName(User))</span>
                <img src="~/images/user.png" class="nav-avatar" />
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="#">Your Profile</a></li>
                <li><a href="#">Edit Profile</a></li>
                <li><a href="#">Account Settings</a></li>
                <li class="divider"></li>
                <li>
                    <form asp-action="LogOut" asp-area="Identity" asp-controller="Account" style="padding: 10px 20px;">
                        <input type="submit" value="LogOut" class="log-out-button">
                    </form>
                </li>
            </ul>
        </li>
    }
else {
    <li>
        <a asp-action="SignIn" asp-controller="Account" asp-area="Identity">SignUp</a>
    </li>
}
</ul>